# POST http://localhost:3000/admin/login HTTP/1.1
# content-type: application/json

# {
#     "email": "andreas.anggara@email.com",
#     "password": "admin123"
# }

GET  http://localhost:3000/admin/employee HTTP/1.1
content-type: application/json
token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhbmRyZWFzLmFuZ2dhcmFAZW1haWwuY29tIiwiYXV0aExldmVsIjoxLCJpYXQiOjE1ODcxMTUyODZ9.NlOuz8Dcrm9bMWUByWnkD1DJBbvaqgKC0yGThYyWVTM"

#

POST http://localhost:3000/admin/addEmployee HTTP/1.1
content-type: application/json
token : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhbmRyZWFzLmFuZ2dhcmFAZW1haWwuY29tIiwiYXV0aExldmVsIjoxLCJpYXQiOjE1ODcxMTAwNDF9.4C2hOZDdazIRPBze2seGIHUgxlZIaAtZ-eq-iEn25Qo"

{
    "name": "Andreas Anggara",
      "password": "user123",
      "email": "andreas.anggara@email.com",
      "birthDate": "2015-03-25",
      "address": "Bogor",
      "phoneNumber": "0812121212",
      "role": "Manager",
      "authLevel": 2,
      "superior": 1,
      "paidLeave": 12
}

POST http://localhost:3000/admin/employee HTTP/1.1
content-type: application/json
token : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhbmRyZWFzLmFuZ2dhcmFAZW1haWwuY29tIiwiYXV0aExldmVsIjoxLCJpYXQiOjE1ODcxMTAwNDF9.4C2hOZDdazIRPBze2seGIHUgxlZIaAtZ-eq-iEn25Qo"

{
    "name": "Andreas Anggara",
      "password": "user123",
      "email": "andreas.anggara@email.com",
      "birthDate": "2015-03-25",
      "address": "Bogor",
      "phoneNumber": "0812121212",
      "role": "Manager",
      "authLevel": 2,
      "superior": 1,
      "paidLeave": 12
}